### ISSUE TITLE
Identifier label radius's don't match

### ISSUE THREAD

**Issue by N6REJ** [Bearsampp/Bearsampp#150]
Borders don't match between article and sidebar.  Lets match them up.
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/1850089/182849554-a1d731a6-872f-4b82-b9c3-102b8aa1b590.png">

**Comment by N6REJ** [comment]
@alain01 @jwaisner got a preference as to which to use?

**Comment by N6REJ** [comment]
I'm leaning towards the more square

**Comment by jwaisner** [comment]
I agree with the squared look.

**Comment by N6REJ** [comment]
Fixed 2022.08.05
