### ISSUE TITLE
Image quality on the logo (prerequisites)

### ISSUE THREAD

**Issue by alain01** [Bearsampp/Bearsampp#163]
Hi,
not very important but it's just a remark.

- Installing "Bearsampp-prerequisites-2022.08.09.exe"
- Executing
The logo is very pixeled.
It doesn't give a good image of what we are going to install
It's blurry and pixelated
![Capture d’écran 2022-08-10 100547](https://user-images.githubusercontent.com/5336960/183849670-6a69c377-4c78-4612-a007-fdb5027619af.png)

**Comment by alain01** [comment]
Same with the "About button" in the Bearsampp application !
![Capture d’écran 2022-08-10 113457](https://user-images.githubusercontent.com/5336960/183868677-bd509c06-e1ea-46ef-b799-c68ac6455464.png)

**Comment by N6REJ** [comment]
damn, I thought I had those fixed. *sigh*
i'll get those fixed , I hope, for september release.

**Comment by N6REJ** [comment]
exporting the source .svg @ 32px gives us a 6dpi output.
![image](https://user-images.githubusercontent.com/1850089/184055531-b00938cd-2d0e-45c9-ba01-f7b22be527e2.png)

**Comment by N6REJ** [comment]
my eyesight isn't good enough to tell if its any better or not...
![image](https://user-images.githubusercontent.com/1850089/184062460-b2b24a0d-5193-4860-9eb8-627515f8f660.png)

**Comment by N6REJ** [comment]
Fixed in https://github.com/Bearsampp/prerequisites/releases/download/2022.08.10/Bearsampp-prerequisites-2022.08.10.exe
![image](https://user-images.githubusercontent.com/1850089/184064230-6cfffcd8-8ea7-425c-9496-7e4ae78cf33f.png)
![image](https://user-images.githubusercontent.com/1850089/184064242-af83ef9a-1045-41de-9965-d653bd359a8f.png)
@alain01 please test

**Comment by alain01** [comment]
- Ok for the pre-requis 2022-08-10 :-)
- Not ok for the "About" windows (Bearswampp)

**Comment by alain01** [comment]
> see http://bearsampp.com/faq/admins/what-software-is-used-to-create-the-prerequisites-packager for directions. ( the major bug there has been reported to Minitek.

Not very important but I can't access with my github login even I click on the link 
![Capture d’écran 2022-08-11 090743](https://user-images.githubusercontent.com/5336960/184081314-4ac5a54f-6148-4ad1-9b8f-a37a0355694d.png)
n

**Comment by N6REJ** [comment]
we're aware of GH login not working we're trying to fix it.  It's a 3rd party issue.

**Comment by N6REJ** [comment]
> * Not ok for the "About" windows (Bearswampp)
*sigh* idk what to do about it.  It's using the same exact svg file as for everything else.
maybe @jwaisner has an idea.

**Comment by N6REJ** [comment]
Fixed with https://github.com/Bearsampp/Bearsampp/commit/66bafe5c00942bc877b702dfec09a4d9263d6cc8
<img width="337" alt="image" src="https://user-images.githubusercontent.com/1850089/184780392-4538c269-b1b9-44cb-9fc3-c5c85f70b44a.png">
