### ISSUE TITLE
Error 404: https://bearsampp.com/doc/?utm_source=bearsampp-2022.08.09

### ISSUE THREAD

**Issue by alain01** [Bearsampp/Bearsampp#168]
Bearsampp version:
2022.08.09

Right click on bearswampp icon on the bottom nav then choose "Help" => 404 error
https://bearsampp.com/doc/?utm_source=bearsampp-2022.08.09

**Comment by N6REJ** [comment]
damn it.. I thought we had all those fixed.. *sigh*...

**Comment by N6REJ** [comment]
This is caused by line 170
```             TplAestan::getItemLink($bearsamppLang->getValue(Lang::HELP), Util::getWebsiteUrl('doc')) . PHP_EOL . ```
in core->tpls->class.tpl.app.php needs to be set to "faq"
```             TplAestan::getItemLink($bearsamppLang->getValue(Lang::HELP), Util::getWebsiteUrl('faq')) . PHP_EOL . ```

**Comment by N6REJ** [comment]
Fixed in https://github.com/Bearsampp/Bearsampp/pull/182
