### ISSUE TITLE
Python not building

### ISSUE THREAD

**Issue by jwaisner** [Bearsampp/Bearsampp#209]
Python currently not building. We are looking into this issue in an attempt to resolve.

**Comment by jwaisner** [comment]
This has been resolved and released latest version: https://github.com/Bearsampp/modules-untouched/releases/tag/python-2022.09.07

**Comment by N6REJ** [comment]
> This has been resolved and released latest version: https://github.com/Bearsampp/modules-untouched/releases/tag/python-2022.09.07

Correct link is https://github.com/Bearsampp/module-python/releases/download/2022.09.07/bearsampp-python-3.10.5.0-2022.09.07.7z
