### ISSUE TITLE
Versions in menu are not alphanumeric

### ISSUE THREAD

**Issue by N6REJ** [Bearsampp/Bearsampp#211]
Version numbering in menus are not correct in their numerical importance.
![image](https://user-images.githubusercontent.com/1850089/188557555-2df9d44e-51fc-41e4-86ad-852d5812e87d.png)

**Comment by N6REJ** [comment]
Due to missing source files that apparently are no longer available we can't update the menu

**Comment by N6REJ** [comment]
see https://github.com/Bearsampp/Bearsampp/pull/236

**Comment by jwaisner** [comment]
Resolved in October release
