### ISSUE TITLE
Memcach(D) broken in 8.1.8 & 8.1.10

### ISSUE THREAD

**Issue by N6REJ** [Bearsampp/Bearsampp#214]
Seems we have an issue with memcache not working in 8.1.8 nor 8.1.10 but DOES work in 8.1.9

**Comment by N6REJ** [comment]
https://github.com/nono303/PHP-memcache-dll/issues/27

**Comment by jwaisner** [comment]
Resolved in this release: https://github.com/Bearsampp/module-php/releases/tag/2022.09.09
