### ISSUE TITLE
Postgres doesn't work with Joomla.

### ISSUE THREAD

**Issue by N6REJ** [Bearsampp/Bearsampp#220]
There is an issue where you get 
![image](https://user-images.githubusercontent.com/1850089/189853828-d2c25ca1-589e-4d81-b783-6af7b1dd7b99.png)
When attempting to install with postgres.
This is caused by a missing entry in "pg_hba.conf.ber" where the local ipv6 info is missing.

```
# TYPE      DATABASE        USER            ADDRESS                 METHOD
host        all             all             127.0.0.1/32            trust
host 		all				all				::1/128					trust
```
needs to be changed in ALL versions of postgres

**Comment by jwaisner** [comment]
resolved by [](https://github.com/Bearsampp/module-postgresql/pull/7)

**Comment by N6REJ** [comment]
yep
