### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by anguslee-wse** [Bearsampp/Bearsampp#255]
> Please follow this guide to file a proper request report : http://bearsampp.com/request

* Name: MongoDB
* Description: 
* Website: 
* License (e.g. Freeware, OSS, GPL, MIT, etc): 
* Comment (anything else which might help): Coming from Neard. It was in Neard. Why is MongoDB not included in Bearsampp?

**Comment by N6REJ** [comment]
We removed it as we did see that it was being used, nor really a need for yet a 3rd database.

**Comment by N6REJ** [comment]
@anguslee-wse we are re-introducing it into Decembers release

**Comment by N6REJ** [comment]
We have looked into this and with the changes that mongo has created in their releases we were unable to make it function in our environment.  While we could've reimplemented 4.x we feel it is too old to include in our updated software system.  
To put it simply they no longer easily support portable versions.
