### ISSUE TITLE
1st launch - Exception in module neard.exe at 000F15A0

### ISSUE THREAD

**Issue by alain01** [Bearsampp/Bearsampp#27]
Hi,
When I launched "neard.exe" i get this:
![Capture d’écran 2021-11-30 144340](https://user-images.githubusercontent.com/5336960/144058923-cfe9a2c3-1cb3-421b-8301-fa7b6a6f177c.png)

**Comment by N6REJ** [comment]
What changed?  I need more info to hunt it down.

**Comment by alain01** [comment]
Humm, I didnt use them,
I used the original prerequisite package (neard)...
Ok, I try this.

**Comment by N6REJ** [comment]
ok, I just got back from the docs so won't work on it today ( had stress test ) but I'll look @ it again tomorrow.
Please make sure all other "servers" are off.  Neard, wamp. xampp, mysql etc.. 
I believe your x64 not x32?

**Comment by alain01** [comment]
OK, I used several PC.
I dont want to test on my PC at home.
I will test tomorrow on my professionnal laptop. (W10 pro 64b too)
I will check  that servers are off, sure.

**Comment by alain01** [comment]
Same error...

**Comment by alain01** [comment]
Ok,
the https://github.com/Bearsampp/Bearsampp/releases/tag/v1.8.3-rc1 version is ok,
but I tested the master branch and I get the error.
I discovered that the size of master version after unzip is very low (21 mb).
The 1.8.3 rc1 directory : 2,7 Go...

**Comment by N6REJ** [comment]
don't go by master, thats pretty much straight neard.  Glad to hear all is ok with the rc-1.

**Comment by N6REJ** [comment]
infact, "Master" is not going to be used anymore.  Everything will be on "main" when its current.

**Comment by alain01** [comment]
Ok, I didnt  know that I should not use the master branch to test...
So, you could close this issue.
