### ISSUE TITLE
Display errors on even when is set to off

### ISSUE THREAD

**Issue by mariantanase** [Bearsampp/Bearsampp#271]
#### Steps to reproduce this issue

1. Edit php.ini (for the actual php version) to not display errors.
2. Start restoring a Joomla 3.10 website with Akeeba Kickstart.

#### Expected behaviour
On the page who display the requirements should Display errors to Off

#### Actual behaviour
On the page who display the requirements it says that Display errors is still On (even after restarting services)

### Configuration
* Bearsampp version and the previous version in case of upgrade:  november 2022
* Operating system: Windows 10
* PHP 7.4

**Comment by N6REJ** [comment]
please update joomla to the latest version and let me know if it still occurs.  Your using very old version of J! and php.

**Comment by mariantanase** [comment]
Sorry, when I said Joomla 3.10, I mean Joomla 3.10.11 which is the latest version.
And even with php 8.0.24 is the same issue.

**Comment by N6REJ** [comment]
ok, I'm 99% sure this is a J! issue but we'll test it.

**Comment by N6REJ** [comment]
by default Bearsampp has display errors on for php.  Go to the menu and turn it off...
![image](https://user-images.githubusercontent.com/1850089/199856586-8d0d6c5f-c91b-42e0-a891-d639c5113892.png)

**Comment by mariantanase** [comment]
Yes I had already done but nothing changes.

![display-errors-on](https://user-images.githubusercontent.com/3976174/199919648-0139c564-7c0a-4fc2-abd4-ef1458f2b76d.png)

**Comment by N6REJ** [comment]
I don't recognize that menu.  Have you modified our layout?

**Comment by mariantanase** [comment]
Sorry for the wrong screenshot.
This is the correct one.

![display-errors-on2](https://user-images.githubusercontent.com/3976174/199950053-4f9132af-4ae1-4223-9e73-e0a67bb7400c.png)

**Comment by mariantanase** [comment]
Ok, I made some other tests and it seems that the message is cause by the Akeeba Kickstart restoration script.
When made a clean install, the display errors check is correct set to off.

**Comment by N6REJ** [comment]
Thanks for the clarification.  So it seems like you would need to be sure its off before you start the restore.  Good thing to know.
that menu layout you made is kind of interesting.
