### ISSUE TITLE
Add Bearsampp to Joomla Doc - Setting up your workstation for Joomla development

### ISSUE THREAD

**Issue by shoulders** [Bearsampp/Bearsampp#274]
**Is your feature request related to a problem? Please describe.**
Bearsampp is not mentiond on this Joomla page https://docs.joomla.org/Setting_up_your_workstation_for_Joomla_development

**Describe the solution you'd like**
Add this software to the list

**Describe alternatives you've considered**
n/a

**Additional context**
Joomla should be promoting Bearsampp and this will help

**Comment by N6REJ** [comment]
Thanks for the suggestion.  Wonderful idea.

**Comment by shoulders** [comment]
i am concerned this is going to get shut automatically.

**Comment by N6REJ** [comment]
@jwaisner can you handle this please?

**Comment by felixkat** [comment]
I attempted to add this but the Joomla Documentation killed me for adding links.  I have written to the sysops to try and get whitelisted.  If approved I can assist with creating a page for setting up Joomla with Bearsampp.

**Comment by N6REJ** [comment]
Thanks, if you run into resistance let me know as I'm on JBS and can poke the right people.

**Comment by N6REJ** [comment]
https://docs.joomla.org/Setting_up_your_workstation_for_Joomla_development

**Comment by N6REJ** [comment]
maybe cause I'm JBS member.  Anything I missed?

**Comment by N6REJ** [comment]
oh, and go to "open source matters" ( osm.com I think ) and let them know whats going on.

**Comment by shoulders** [comment]
https://www.opensourcematters.org/

**Comment by felixkat** [comment]
> maybe cause I'm JBS member. Anything I missed?

I added the entry just as you have done but the wiki blocked me for spamming.  I tried reaching out to a few people but didn't get a response.  They should be welcoming people with open arms who want to contribute to the documentation, Joomla isn't exactly known for detailed docs.  😆

**Comment by N6REJ** [comment]
they do want doc folks... badly.. check the teams and apply to the documentation team.
