### ISSUE TITLE
Add a specific link to version comparison for the homepages

### ISSUE THREAD

**Issue by shoulders** [Bearsampp/Bearsampp#275]
**Is your feature request related to a problem? Please describe.**
The version comparison was difficult to find and not where I expected it to be. I could not use google to find this information because the word `comparison` was not used, I searched for 'Bearsampp version comparison'
On the github homepage the phrase `It also offers several versions` is used but that is all that is mentioned there.

**Describe the solution you'd like**
A specific link or text on the Bearsampp website and Github repo pointing to the version comparison section on the FAQ page. The term `Version Comparison` or `Compare Versions` needs to be used to help Google and other search engines.

**Describe alternatives you've considered**
You move the version comparison to the bearsampp github repo homepage (readme.md)

**Additional context**
Version comparisons are usual mention on the homepages of github projects and/or websites so the end user can find this information easily.

**Comment by N6REJ** [comment]
We'll look into the best way to implement this.  Thank you for reporting.

**Comment by shoulders** [comment]
i am concerned this is going to get shut automatically.

**Comment by N6REJ** [comment]
resolved here https://bearsampp.com/get-started
