### ISSUE TITLE
Add version descriptions

### ISSUE THREAD

**Issue by shoulders** [Bearsampp/Bearsampp#276]
**Is your feature request related to a problem? Please describe.**
There are no descriptions of the different versions of Bearsampp. There is a comparison table, but that is all I could find.

**Describe the solution you'd like**
I would like an explantion of who each of the different versions of Bearsampp are aimed at (Full/Basic/Lite), and perhaps how they compare to WAMPP and XAMPP

**Describe alternatives you've considered**
n/a

**Additional context**
This will help newcomers to development and those like me with a little bit more knowledge. Without this information everyone will just download and install the `FULL` version which perhaps defats the object of having the different versions.

**Comment by N6REJ** [comment]
Thanks for the report.  We'll look into the best way to implement this.

**Comment by shoulders** [comment]
i am concerned this is going to get shut automatically.

**Comment by N6REJ** [comment]
from one perspective the difference between versions is minimal in that you can convert one version to another relatively easily.  Thats the whole purpose of this program in that your not locked into anything.
>Describe the solution you'd like
I would like an explantion of who each of the different versions of Bearsampp are aimed at (Full/Basic/Lite), and perhaps how they compare to WAMPP and XAMPP

I'm not sure that that's practical as they could change their behavior at any time without our knowledge and each can be customized beyond the default.  At some point we have to assume dev's know what programs they require.
I Have updated the Getting started page to hotlink to the FAQ which should solve any ambiguity.
I'll leave it up to @jwaisner to decide if we need/should go into such a detailed explanation of how we compare to xampp/wamp beyond the MAJOR fact that we are portable and they are not.  THAT is our market.

**Comment by shoulders** [comment]
it didnt need a indepth explantation, but a paragraph/sentence per version.

**Comment by N6REJ** [comment]
After our meeting we've decided to leave it as is.  The dev's that would use our product know what programs they need and can easily check the chart to find out which automatically provide those features.  If they decide they need more features later it can be added to that feature.  Sorry this isn't what you wanted.
