### ISSUE TITLE
Documention: issues with LITE version on comparison table

### ISSUE THREAD

**Issue by shoulders** [Bearsampp/Bearsampp#277]
### Behaviour
This is about documentation issue rather than a bug with the software

#### Steps to reproduce this issue

- Look on the version compare in the FAQ (https://bearsampp.com/faq/general/versions)
- You will see the `LITE` version has `phpMyAdmin` installed but there are no corresponding database servers installed (MariaDB/MySQL)

#### Expected behaviour

> The lite version should have at least one Database service installed so `phpMyAdmin` can be used or `phpMyAdmin` should be removed as it is pointless.

#### Actual behaviour

> No DB servers re installed

### Configuration

n/a

### Logs
n/a

### Solution
The `LITE` version should have at least `MariaDB` installed by default like `XAMPP` and `WAMPP` or `phpMyAdmin` should be removed as it is pointless.

If these options  can be downloaded through the Bearsampp console after the intial download, then the legend should be updated to reflect this.

**Comment by N6REJ** [comment]
Thanks for the report.  MySQL is included by default.  This was an error in our documentation and has since been corrected.
