### ISSUE TITLE
Phpmyadmin 4p9 warnings

### ISSUE THREAD

**Issue by mariantanase** [Bearsampp/Bearsampp#28]
### Behaviour
There are warnings when open phpmyadmin
#### Steps to reproduce this issue
When open http://localhost/phpmyadmin, insert default credentials.
It show some warnings.

### Configuration

* Neard version: neard-basic-1.8.3-rc1-SNAPSHOT 
* Operating system: Win10x6

![phpmyadmin-warnings](https://user-images.githubusercontent.com/3976174/144196075-57f4e734-0341-4822-86f9-fddcc7effb29.png)

P.S. How can I update phpmyadmin and make default ?

**Comment by mariantanase** [comment]
Switch to neard-basic-1.8.2.7z
No warnings.

I tried then to copy the apache2.4.51 module from your package (neard1.8.3 rc1) to the neard-basic-1.8.2 and then switch to Apache 2.4.51. But doesn't start. 
I think that are some config errors on apache 2.4.51 module.

**Comment by N6REJ** [comment]
I'll look into this.  phpmyadmin needs an update ( which I think I released, check announcements ) but I think your running into a php8/apache clash.  I'll add it to my todo list.

**Comment by mariantanase** [comment]
You can provide info on how to change phpmyadmin with the latest neard-phpmyadmin-5.1.1-r12.7z ?
(because the procedure is not similar to that of changing a php package)

**Comment by mariantanase** [comment]
>  but I think your running into a php8/apache clash. I'll add it to my todo list.

And you're right. If I switch to php 7.4.x there no more warnings.

**Comment by N6REJ** [comment]
Should be exactly the same, I'll look into it.

**Comment by N6REJ** [comment]
phpmyadmin 5.1.1 release is broken.  Checking into whats going on.  issue raised on http://github.com/Bearsampp/modules-phpmyadmin repo

**Comment by mariantanase** [comment]
Hi, can you fix this issue ? 
Or do I need to turn back to PHP 7.4 ?

**Comment by N6REJ** [comment]
I've been really sick so I lost track of what was what.
If you can get by with php 7.4 temporarily that would be great.  I'll try really hard to get back on track.

**Comment by mariantanase** [comment]
Sorry to hear about your health. Hope you are well now.
About issue, don't worry, I have already changed to php 7.4 in my development environment.

**Comment by N6REJ** [comment]
Appreciate that.  I'm getting there.  Being older has its limitations.

**Comment by alain01** [comment]
Hello @N6REJ ,
rest well and get well
