### ISSUE TITLE
WSH (Windows Script Host) link broken on bearsampp.com

### ISSUE THREAD

**Issue by shoulders** [Bearsampp/Bearsampp#280]
on the page https://bearsampp.com/get-started the `WSH (Windows Script Host)` link point to a missing page [WSH (Windows Script Host)](https://support.microsoft.com/en-us/kb/232211)

**P.S.** Would you consider creating a repo to report https://bearsampp.com/ website bugs and features or are you happy with them getting reported here?

**Comment by N6REJ** [comment]
your welcome to post them here.  If you'd like you can certainely join our dev team https://github.com/orgs/Bearsampp/teams

**Comment by N6REJ** [comment]
>Windows Script Host is distributed and installed by default on [Windows 98](https://en.wikipedia.org/wiki/Windows_98) and later versions of Windows

**Comment by shoulders** [comment]
I will bear the invite in mind, i am just transitioning from IT to programming and have a few things to sort as always.
