### ISSUE TITLE
cannot create new folder for Apache 'Add virtual host'

### ISSUE THREAD

**Issue by shoulders** [Bearsampp/Bearsampp#282]
**Is your feature request related to a problem? Please describe.**
This is a simple feature but used all the time. as you can see in the browse window there is no option to create a new folder.
![image](https://user-images.githubusercontent.com/319997/201725435-285a8a83-499b-4a1b-9edf-0dd5cae76a63.png)

**Describe the solution you'd like**
Add a create new folder button

**Describe alternatives you've considered**
n/a

**Additional context**
- This might be already added, (I am a newbie), an option to allow for www and non-www domains when adding a virtual domain.
- The greyed out document root does not update when you change the server name
- should server name be called `domain`?

**Comment by N6REJ** [comment]
> **Is your feature request related to a problem? Please describe.** This is a simple feature but used all the time. as you can see in the browse window there is no option to create a new folder. ![image](https://user-images.githubusercontent.com/319997/201725435-285a8a83-499b-4a1b-9edf-0dd5cae76a63.png)

> * This might be already added, (I am a newbie), an option to allow for www and non-www domains when adding a virtual domain.

When you use the host editor it automatically creates both www and non-www domain names to the windows host file.

> * The greyed out document root does not update when you change the server name
@jwaisner  I don't think this can be changed without a delphi rewrite but we can check into it.

> * should server name be called `domain`?
Good question.

**Comment by shoulders** [comment]
SERVER_NAME or HTTP_HOST (chicken or egg situation ???)
- https://www.askapache.com/htaccess/mod_rewrite-variables-cheatsheet/#SERVER_NAME
- https://www.askapache.com/htaccess/mod_rewrite-variables-cheatsheet/#HTTP_HOST

----

I can create a new issue if need but can this message be added to the dialogue, not all systems add both www and non-www automatically, i.e. xampp

![image](https://user-images.githubusercontent.com/319997/201746743-e0454c51-8d9b-49a8-add1-f2eb637ed2b2.png)

**Comment by N6REJ** [comment]
> SERVER_NAME or HTTP_HOST (chicken or egg situation ???)
> 
> * https://www.askapache.com/htaccess/mod_rewrite-variables-cheatsheet/#SERVER_NAME
> * https://www.askapache.com/htaccess/mod_rewrite-variables-cheatsheet/#HTTP_HOST
> 
> I can create a new issue if need but can this message be added to the dialogue, not all systems add both www and non-www automatically, i.e. xampp
> 
> ![image](https://user-images.githubusercontent.com/319997/201746743-e0454c51-8d9b-49a8-add1-f2eb637ed2b2.png)

Sorry, I'm not understanding the issue.  As soon as you use the Host editor tool, 
![image](https://user-images.githubusercontent.com/1850089/201810513-5e897fd3-39af-40b4-8126-160927274d91.png)

it will create both www & non-www

**Comment by shoulders** [comment]
I was on about `Add Virtual Host` and adding a note there, but you are on about `HostsEditor` so I will have to investigate what the difference is.

I assumed `Add Virtual Host` was a similar function to cPanel `Addon Domain`

**Comment by N6REJ** [comment]
> I was on about `Add Virtual Host` and adding a note there, but you are on about `HostsEditor` so I will have to investigate what the difference is.
> 
> I assumed `Add Virtual Host` was a similar function to cPanel `Addon Domain`

that is correct.  But you have "dns" to worry about also which is what your hosts editor does.  Windows has to know where myhost.local is.  I could be any of 1000 trillion places.  Hosts editor is where you do that.

**Comment by N6REJ** [comment]
Winbinder is no longer being maintained for many years and I don't see anyway to allow for folder creation with the current implementation.
Until we acquire the funding to completely rewrite the UI ( which we would love to do ) we won't be able to implement this.
