### ISSUE TITLE
difference between the doc and the reality on the last version (typo error on doc ?)

### ISSUE THREAD

**Issue by alain01** [Bearsampp/Bearsampp#287]
Hi,
(My mini come back) ! 
happy new year and congratulations for this very good work

Not a bug, just a mini typo error.

I used the very last version 2022.12.04
See captures:
![Capture d’écran 2023-01-11 225837](https://user-images.githubusercontent.com/5336960/211927412-6c2c4e1c-c983-46b6-8aaa-e09237128c74.png)
![Capture d’écran 2023-01-11 225746](https://user-images.githubusercontent.com/5336960/211927432-32366111-318f-4275-8b1f-247c15fad649.png)

So the default version of PHP with the lastest Bearsampp is 8.1.13, not 8.2.0

May be I missed something,
If it's the case, sorry for this bad noise ! 
Alain from France ;-)

**Comment by N6REJ** [comment]
welcome back.  Fixed.
