### ISSUE TITLE
Apache 2.4.57

### ISSUE THREAD

**Issue by jwaisner** [Bearsampp/Bearsampp#305]
Apache released an update which fixes bugs within Apache.

**Comment by N6REJ** [comment]
Apachehaus latest release is 2.4.55 https://www.apachehaus.com/cgi-bin/download.plx

**Comment by jwaisner** [comment]
@N6REJ , we should look at moving to the OpenSSL 3.0.x version of Apache. The 1.1.1 version we are currently on EOLs in September.

**Comment by N6REJ** [comment]
There is a major problem with that.  See the notes here https://www.apachehaus.com/

**Comment by N6REJ** [comment]
pr created

**Comment by N6REJ** [comment]
Wasn't this merged?

**Comment by N6REJ** [comment]
@jwaisner has this been merged?
