### ISSUE TITLE
New Version Available - Broken Link

### ISSUE THREAD

**Issue by felixkat** [Bearsampp/Bearsampp#309]
#### Steps to reproduce this issue

1.  Click on the "New Version Available Link from local page.

#### Expected behaviour

> Should link to the latest or new version Github page.

#### Actual behaviour

> Redirects to 404 page on Github

### Configuration

Dec 5, 2022 (2022-12-04)

This may be a one off but the link doesn't work due to missing leading zeros on the URL for the date.

Links are being directed to:-

https://github.com/Bearsampp/Bearsampp/releases/tag/2023.05.09

Actual link is:-

https://github.com/Bearsampp/Bearsampp/releases/tag/2023.5.9

Only a minor thing but I thought I'd point it out.

![image](https://github.com/Bearsampp/Bearsampp/assets/1116451/f4db7044-e402-4376-ab79-11411f3fb624)

Also the X doesn't remove the notification, I'm not sure if it's supposed to!

**Comment by N6REJ** [comment]
thanks for the report.  I've fixed the issue.  we had the old semver style in the update file.
As for the X I agree with you.  We've tried to sort it out but will try harder.

**Comment by felixkat** [comment]
I can confirm this is working.
