### ISSUE TITLE
License

### ISSUE THREAD

**Issue by brianteeman** [Bearsampp/Bearsampp#321]
The license terms of ln clearly prevent its inclusion in bearsampp

https://github.com/Bearsampp/Bearsampp/blob/5f65834d6724ed226572f2534c64ce2baa9fb920/core/libs/ln/license.txt#L24

**Comment by N6REJ** [comment]
we'll look into it.  ty for bringing it to my attention.

**Comment by N6REJ** [comment]
```
Hi

It’s perfectly fine you can use ln.exe for your open source web server software for free as mentioned below

License granted. ☺️

    Ciao Hermann
 ```
