### ISSUE TITLE
PHP Module Update - 8.2.10, 8.1.23, 8.0.30

### ISSUE THREAD

**Issue by jwaisner** [Bearsampp/Bearsampp#323]
Bugfix releases for PHP.

**Comment by N6REJ** [comment]
with https://github.com/Bearsampp/module-php/commit/3d52ca20d9c23f8dfd124f5325adb105480071a3 imagick fails to function properly.  Waiting on dev.
<img width="679" alt="image" src="https://github.com/Bearsampp/Bearsampp/assets/1850089/54eae28c-cd6c-45cc-9120-ae2385de7cf8">

**Comment by N6REJ** [comment]
fixed with pr https://github.com/Bearsampp/module-php/pull/31
