### ISSUE TITLE
Python Module Update - 3.11.5 & 3.10.13

### ISSUE THREAD

**Issue by jwaisner** [Bearsampp/Bearsampp#332]
Minor version update and bug fix releases.

**Comment by N6REJ** [comment]
having an issue building script 
![image](https://github.com/Bearsampp/Bearsampp/assets/1850089/ae313421-1f1b-449c-817d-713b712b0274)

**Comment by N6REJ** [comment]
@jwaisner can you try to build this please

**Comment by jwaisner** [comment]
3.11.8 released https://github.com/Bearsampp/module-python/releases/tag/2024.3.29
