### ISSUE TITLE
Xdebug function changed with xdebug 3

### ISSUE THREAD

**Issue by N6REJ** [Bearsampp/Bearsampp#343]
As of xdebug 3 most of the functions have been renamed.
as a result php.ini needs its xdebug section changed to as follows.
```
[xdebug]
xdebug.mode = debug
xdebug.client_host=localhost
```
here is the upgrade guide for moving from xdebug 2 to xdebug 3 https://xdebug.org/docs/upgrade_guide

This will require an entry/update in our FAQ section.
This also changes the port from 10000 that we used to have to 9003 that xdebug now has as the default port.
we can retain the old value by using ```xdebug.client_port = 10000``` if we wish.
I think this major change is going to require us to hotfix all versions of php that use xdebug 3

**Comment by jwaisner** [comment]
Fixed and FAQ is updated.
